.TH bml 1 "2019" "bml"

.SH NAME
bml \-\- blur markup language command line utility

.SH SYNOPSIS
bml [options] [path]

.SH DESCRIPTION
Render a bml document read from stdin or a file, if given.

Prints result to STDOUT.

If any error occurs during processing, exit code 1 is returned.

.SH OPTIONS
.TP
.BR \-h ", " \-\-h ", " \-help ", " \-\-help
Print help and quit

.TP
.BR \-v ", " \-\-version
Print version information and quit

.TP
.BR \-\-seed " INTEGER"
Set the random seed to be used for the render run

.TP
.BR \-\-no\-eval
Disable Javascript evaluation

.TP
.BR \-\-render\-markdown
render the document as markdown to HTML


.TP
.BR \-\-no\-whitespace\-cleanup
disable whitespace cleanup

.SH BUG REPORTS
Please report bugs at https://github.com/ajyoon/bml/issues

.SH AUTHOR
Andrew Yoon (andrew@nothing-to-say.org)

.SH LICENSE
BSD 3-Clause, 2017
