language: node_js
node_js:
  - "8"
script:
  - npm install --no-optional -g coveralls
  - nyc npm test && nyc report --reporter=text-lcov > coverage.lcov
after_success:
  - cat coverage.lcov | coveralls
